#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
    push:
        branches-ignore: [master, main]
        # Remove the line above to run when pushing to master
    pull_request:
        branches: [master, main]

###############
# Set the Job #
###############
jobs:
    build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

        ##################
        # Load all steps #
        ##################
        steps:
            ##########################
            # Checkout the code base #
            ##########################
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  # Full git history is needed to get a proper
                  # list of changed files within `super-linter`
                  fetch-depth: 0

            ##########################
            # Set up Node.js         #
            ##########################
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            ##########################
            # Install dependencies   #
            ##########################
            - name: Install dependencies
              run: npm install prettier

            ##########################
            # Run Prettier           #
            ##########################
            - name: Run Prettier
              run: npx prettier --config .prettierrc.yaml --check .

            ################################
            # Run Linter against code base #
            ################################
            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  VALIDATE_ALL_CODEBASE: false
                  # Change to 'main' if your main branch differs
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: .prettierrc.yaml
                  VALIDATE_YAML: true
                  VALIDATE_MARKDOWN: true
                  VALIDATE_JSON: true
                  VALIDATE_JS: true